# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstruct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangobasenode',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='comment'),
        ),
    ]
