# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstruct', '0003_auto_20160616_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoDependencyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain_prerequisite', models.CharField(max_length=1000, verbose_name='Explain why prerequsite is needed')),
                ('explain_usedfor', models.CharField(max_length=1000, verbose_name='Explain the application')),
                ('level', models.CharField(default='HS', max_length=1000, verbose_name='Educational level')),
                ('prerequisite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstruct.DjangoBaseNode')),
                ('usedfor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstruct.DjangoBaseNode')),
            ],
        ),
        migrations.AddField(
            model_name='djangobasenode',
            name='prerequsites',
            field=models.ManyToManyField(related_name='usedfors', through='djstruct.DjangoDependencyRelation', to='djstruct.DjangoBaseNode'),
        ),
    ]
