# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstruct', '0004_auto_20160616_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangodependencyrelation',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites_set', to='djstruct.DjangoBaseNode'),
        ),
        migrations.AlterField(
            model_name='djangodependencyrelation',
            name='usedfor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usedfors_set', to='djstruct.DjangoBaseNode'),
        ),
    ]
